services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: WEB_CONCURRENCY
        value: 4