apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: django-project
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  
