apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: django-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: web
          image: web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
            - secretRef:
                name: db-secret
