apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: django-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: your_dockerhub_username/your_image_name:latest
          command: ["celery", "-A", "project", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
