apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: django-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      initContainers:
        - name: wait-for-web
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for web:80..."
              until nc -z web 80; do
                echo "Web not available yet, sleeping..."
                sleep 2
              done
              echo "Web is up!"
      containers:
        - name: celery-beat
          image: web:latest
          imagePullPolicy: Never
          command: ["celery", "-A", "monitoring_platform", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
