name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Build images
        run: docker compose -f docker-compose.yml --env-file .env build

      - name: Start dependent services (db, redis) in background
        run: docker compose -f docker-compose.yml --env-file .env up -d db redis

      - name: Wait for database to be ready
        run: |
          until docker compose exec db pg_isready -U ${{ secrets.DB_USER }}; do
            echo "Waiting for database..."
            sleep 3
          done

      - name: Run migrations
        run: docker compose -f docker-compose.yml --env-file .env run --rm web python manage.py migrate

      - name: Run tests
        run: docker compose -f docker-compose.yml --env-file .env run --rm web pytest

      - name: Shutdown all services
        if: always()
        run: docker compose -f docker-compose.yml down -v
