name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      - name: Copy example .env
        run: cp .env.example .env

      - name: Build and run containers
        run: docker compose -f docker-compose.yml --env-file .env up -d --build

      - name: Wait for database to be ready
        run: sleep 10  # Можно заменить на healthcheck в будущем

      - name: Run migrations
        run: docker compose -f docker-compose.yml --env-file .env run --rm web python manage.py migrate

      - name: Run tests
        run: docker compose -f docker-compose.yml --env-file .env run --rm web pytest

      - name: Stop and remove containers
        if: always()
        run: docker compose -f docker-compose.yml --env-file .env down -v
