name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Build and start services
        run: docker compose -f docker-compose.yml --env-file .env up -d --build

      - name: Run migrations
        run: docker compose -f docker-compose.yml --env-file .env exec web python manage.py migrate

      - name: Run tests
        run: docker compose -f docker-compose.yml --env-file .env exec web pytest

      - name: Shutdown services
        if: always()
        run: docker compose -f docker-compose.yml down -v
